spring:
  datasource:
    url: ${MY_DB}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
  # sql:
  #   init:
  #     mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[format_sql]": true
        "[show_sql]": true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace

  mail:
    host: smtp.gmail.com
    port: ${SMTP_PORT}
    usename: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

server:
  port: 8082
